project:
  type: book
  output-dir: docs

book:
  title: "Was ist Zukunftsökonomie?"
  author: "Prof. Dr. Jan S. Voßwinkel"
  # date: "18.3.2024
  subtitle: "Sommersemester 2024"
  language:  _language.yml
  chapters:
    - index.qmd
    - intro.qmd
    - Zukunft.qmd
    - Oekonomie.qmd
    - Beobachten.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

